### ISSUE TITLE
Multiple domains not working

### ISSUE THREAD

**Issue by ScorpSoul** [GuilleGF/hassio-ovh#13]
I've trying to setup multiple domains, and I get an error:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/ovh/__init__.py", line 66, in async_setup
    result = await _update_ovh(session, domain, user, password)
  File "/config/custom_components/ovh/__init__.py", line 93, in _update_ovh
    _LOGGER.warning("Updating OVH failed: %s => %s", domain, OVH_ERRORS[body.strip()])
KeyError: 'badfqdn'

I've tried manually and the credentials are working.
on yaml I tried 
domain: test.test.com,test1.test.com
and domain: "test.test.com,test1.test.com"
with no luck. Am I doing something wrong?

**Comment by ScorpSoul** [comment]
Not merged, understood
