### ISSUE TITLE
Bug while retrieving IP

### ISSUE THREAD

**Issue by mbaumanndev** [GuilleGF/hassio-ovh#3]
Hello,

I just installed the hassio-ovh component on my setup, and it seems that the service that should return an IP doesn't return one in my case. I got the following error back from OVH :

```
2020-12-13 19:38:04 ERROR (MainThread) [homeassistant.setup] Error during setup of component ovh
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/config/custom_components/ovh/__init__.py", line 63, in async_setup
result = await _update_ovh(session, domain, ip, user, password)
File "/config/custom_components/ovh/__init__.py", line 107, in _update_ovh
"Updating OVH failed: %s => %s", domain, OVH_ERRORS[body.strip()]
KeyError: '<!DOCTYPE html>\n\t<html>\n\t <head>\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1">\n\t\t<meta charset="utf-8">\n\t\t<title>Application Error</title>\n\t\t<style media="screen">\n\t\t html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t }\n\t\t html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t }\n\t\t iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t }\n\t\t</style>\n\t </head>\n\t <body>\n\t\t<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>\n\t </body>\n\t</html> n\'est pas une ip'
```

I don't know if someone encountered this issue before, but here's how I proceed to install the component :

- I downloaded the latest release available
- I extracted the archive in the `custom_components/ovh` folder
- I wrote a config like shown in the doc in the `config/configuration.yml` file of Home Assistant
- I restarted Home Assistant

**Comment by GuilleGF** [comment]
In the next release use local IP https://github.com/GuilleGF/hassio-ovh/releases/tag/1.1.0
